name: PlayerStatuePlugin
main: com.skytechbytes.testplugin.PlayerStatuePlugin
version: 1.0
softdepend: [WorldGuard]
api-version: 1.13
commands:
   statue:
      description: Make a player statue based on a certain model and in a certain orientation
      usage: /statue <Username> [default|slim|legacy] [xy|xz|yz]
permissions:
   playerstatuecreatorx.createStatue:
      description: Allow creation of a statue
      default: true
   playerstatuecreatorx.bypass:
      description: Create a statue, bypassing material requirements
      default: op
   playerstatuecreatorx.specialOrientation:
      description: Allows creation of statues in the xz and yz plane. Orientation unpredictable so Admin only!
      default: op
   playerstatuecreatorx.override:
      description: Player statue is created and overwrites blocks (usually just skips if not air)
      default: op