name: PlayerStatuePlugin
main: com.skytechbytes.testplugin.PlayerStatuePlugin
version: 1.6
author: SkyTechBytes
softdepend: [WorldGuard]
api-version: 1.13
commands:
   statue:
      description: Make a player statue based on a certain model and in a certain orientation
      usage: /statue <Username> [glass|concrete|terracotta|planks|gray|wool] [default|slim|legacy] [xy|xz|yz] 
   undostatue:
      description: Undo the last statue created by ANYONE on the server
      usage: /undostatue
permissions:
   playerstatuebuilderx.createStatue:
      description: Allow creation of a statue
      default: true
   playerstatuebuilderx.bypass:
      description: Create a statue, bypassing material requirements
      default: op
   playerstatuebuilderx.specialOrientation:
      description: Allows creation of statues in the xz and yz plane. Orientation unpredictable so Admin only!
      default: op
   playerstatuebuilderx.override:
      description: Player statue is created and overwrites blocks (usually just skips if not air)
      default: op
   playerstatuebuilderx.noWait:
      description: The player does not need to wait out the cooldown to make the statue - 5 minutes is default
      default: op
   playerstatuebuilderx.undo:
      description: The player is allowed to undo the last statue created by ANYONE on the server (no material refunds). You must have "override" permissions for this to work
      default: op